echo "Content-Type: text/html"
echo
echo "Hello !!"#echo "<h1>Hello hello.sh !!</h1>"
# echo "<p>AUTH_TYPE = \"$AUTH_TYPE\"</p>"
# echo "<p>CONTENT_LENGTH = \"$CONTENT_LENGTH\"</p>"
# echo "<p>CONTENT_TYPE = \"$CONTENT_TYPE\"</p>"
# echo "<p>GATEWAY_INTERFACE = \"$GATEWAY_INTERFACE\"</p>"
# echo "<p>PATH_INFO = \"$PATH_INFO\"</p>"
# echo "<p>PATH_TRANSLATED = \"$PATH_TRANSLATED\"</p>"
# echo "<p>QUERY_STRING = \"$QUERY_STRING\"</p>"
# echo "<p>REMOTE_ADDR = \"$REMOTE_ADDR\"</p>"
# echo "<p>REMOTE_HOST = \"$REMOTE_HOST\"</p>"
# echo "<p>REMOTE_IDENT = \"$REMOTE_IDENT\"</p>"
# echo "<p>REMOTE_USER = \"$REMOTE_USER\"</p>"
# echo "<p>REQUEST_METHOD = \"$REQUEST_METHOD\"</p>"
# echo "<p>REQUEST_URI = \"$REQUEST_URI\"</p>"
# echo "<p>SCRIPT_NAME = \"$SCRIPT_NAME\"</p>"
# echo "<p>SERVER_NAME = \"$SERVER_NAME\"</p>"
# echo "<p>SERVER_PORT = \"$SERVER_PORT\"</p>"
# echo "<p>SERVER_PROTOCOL = \"$SERVER_PROTOCOL\"</p>"
# echo "<p>SERVER_SOFTWARE = \"$SERVER_SOFTWARE\"</p>"