#ifndef CONFIGERRORTYPE_HPP
# define CONFIGERRORTYPE_HPP

enum ConfigErrorType
{
    UNKNOWN_DIRECTIVE,
    NOT_ALLOWED_DIECTIVE,
    INVALID_NUM_OF_ARGS,
    INVALID_PARAMETER,
    NO_SEMICOLON,
    UNEXPECTED,
    SYNTAXERROR
};

#endif
