#ifndef CONFIGERRORTYPE_HPP
# define CONFIGERRORTYPE_HPP

enum ConfigErrorType
{
    INVALID_NUM_OF_ARGS,
    NO_OPEN_DIRECTIVE,
    NOT_ALLOWED_DIRECTIVE,
    UNEXPECTED,
    UNKOWN_DIRECTIVE
};

#endif
